apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme1
spec:
  encryptedData:
    token: AgCTZgIFsiHtcKeRM+5JGXzkpSWQKUUlJngspNkWG9jI6NHMDTOzhIvKE6vfPY09rt0xSUaaZ4rDrL8WoXBlr3vQ+Ss3xhVK+sQzWbKa8w7sPPc1GWIEkFMD+326J58onu7CkjXdGW3YfPZC9jCGXE2aIAuSbMh6EFUCtmeF5AzdWMxvVn8mowhzxsUGVEIiLb2wULJq/AIds6Qk8RqNSoWpl0xJ+0X2+bL+I35LgwkgH9Fb9hISomwGFxOvXlluYfTQ9HBIrm6yjHR8nAgKaHPEWCsTH+ah2faZQ3WrBB17tOFdXQb3U4yzwndV6P997wXhbKOXp9dgfeVtJOfRJS+bejyoulWxdKTMmHuG2AB0Ut3d/S826D+mAo3nnhAi9hXn+IgDQ4flcekQbDUV/b0VP9cSCfIqp/59MpzZQMpU0oq9CAWQ/F5KNF3LJR4f5omehgoR+shlR1MnKtw1md7pv+UcNh4SbV8ze8rQ8vGnl7wjIESbXl8hi8Hov8M5ZPf4++vkJg9MO6N+UPGme8Jh6xdpS3J5eUo8QQT05csmPxHjoMADmhp2D5XYPhf0+M4K4llFSasl/kc5shQxHItRK6flZyKkQKPPJhogdBtFNtKL8Mn7U86uiL95Gs6lpZbdYCW+6QT8rbON15H/k21Q9grksEWWcx6K3qdtDiCwZ1YBmjeWTAHQ0k9b01Kh6DTU77sZ1WRou0NeKQlPbCed1K57b7nmUxjd4XzS/klHjvf6fpmbGHBg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme1

