apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgBuUslb8GwKEBdV0Ut24C/p4JV4kpAUz6CG6SOP9van6xPVT7Jg0MOoxTZ3YSplR6kapdFZ/waZFPZGY/ZPByfancClHaP3ghN66n1eGN/qc+5bh1MFyK0XbDk+OfhTOGF+MIq2LT3IlLykLIE2+MYEyZ77RynnDCDJ/B+5c2sWDwXpLDDkBzcIX3KQvbc2msvWR8iWZlNTFQf/LROqk5nWO5HqIadsAnxtErVXKzKwjHYePWDt5ipxaHosUGEfrtpxlE3AGynxjnyRA1s3Zm8Ok7KeaIuOBnS0qFNrA80+CsJvBw0ZRgOl14aLjoUghnDtjimpJGz9E9/k0OnmXGukKVDM2kNMkOy83o5fq8NINmEaF+Nf8g7GnZA6QxWzypITS50lOhmmbA7B6jGUXRaWLrHbdZSS0OiRkvdQ/uoWLWBJeDiRqcMCUe7MiQJCQUoWfw5yzOSrbXVPtJyrqT/k4VIz7VSaJphj3lJOVolI0AU9bDkwKmIfIjXCztXOzLXdnm7MISHUaYYxhaqQsGIcPgDAzw34HhHsbg0z0w0/sf4lfj8HIia9EaWh8HYVN9ngXRNTXBr7wQUfKhOiPTXMaNhwQlTQCn9gLS1HwSdonBXrvcmo6WspAdkekyiHNrU7JOQn1J+EtsfEvn+0KBfhn+YuOkduuJxEmQfhYU5dDi8dnRb3yfXCvPLRIsLUEbv9FxXmLn72yJXG/qqPX4E0NGfiDBLXchn7bAg9I8B4rvEHWeGLgTJU
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

