apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-config
spec:
  params:
    - name: is-config-directory
      type: string
    - name: is-infra-directory
      type: string
    - name: is-configuration-keystore
      type: string
    - name: is-configuration-truststore
      type: string
    - name: is-configuration-setdbparms
      type: string
    - name: is-configuration-serverconf
      type: string
    - name: is-configuration-policyproject
      type: string
    - name: is-configuration-loopbackdatasource
      type: string
    - name: rendered-config-directory
      type: string
    - name: repo-directory
      type: string
    - name: user-name
      type: string
    - name: user-email
      type: string
    - name: user-home
      type: string
      default: "/root"
    - name: kustomization-path
      type: string
    - name: branch_name
      type: string
  results:
    - name: configurations
      description: ''
  steps:
    - name: setup-configuration
      env:
        - name: IS_CONFIG_DIRECTORY
          value: $(params.is-config-directory)
        - name: IS_INFRA_DIRECTORY
          value: $(params.is-infra-directory)
        - name: IS_CONFIGURATION_KEYSTORE
          value: $(params.is-configuration-keystore)
        - name: IS_CONFIGURATION_TRUSTSTORE
          value: $(params.is-configuration-truststore)
        - name: IS_CONFIGURATION_SETDBPARMS
          value: $(params.is-configuration-setdbparms)
        - name: IS_CONFIGURATION_SERVERCONF
          value: $(params.is-configuration-serverconf)
        - name: IS_CONFIGURATION_POLICYPROJECT
          value: $(params.is-configuration-policyproject)
        - name: IS_CONFIGURATION_LOOPBACKDATASOURCE
          value: $(params.is-configuration-loopbackdatasource)
        - name: WORKSPACE_PATH
          value: $(workspaces.workspace.path)
        - name: RENDERED_CONFIG_DIRECTORY
          value: $(params.rendered-config-directory)
      image: image-registry.openshift-image-registry.svc:5000/ci/sh-tools
      script: |
        # (script content)
      workingDir: $(workspaces.workspace.path)
    - name: update-kustomization
      env:
        - name: DESTINATION_DIRECTORY
          value: $(workspaces.workspace.path)/$(params.rendered-config-directory)
        - name: CONFIGURATIONS_PATH
          value: $(results.configurations.path)
        - name: KUSTOMIZATION_PATH
          value: $(workspaces.workspace.path)/$(params.kustomization-path)
      image: image-registry.openshift-image-registry.svc:5000/ci/sh-tools
      script: |
        # (script content)
    - name: push-configuration
      env:
        - name: GIT_USER_NAME
          value: $(params.user-name)
        - name: GIT_USER_EMAIL
          value: $(params.user-email)
        - name: WORKSPACE_SSH_DIRECTORY_PATH
          value: $(workspaces.ssh-directory.path)
        - name: PARAM_USER_HOME
          value: $(params.user-home)
        - name: BRANCH_NAME
          value: $(params.branch_name)
      workingDir: $(workspaces.workspace.path)/$(params.repo-directory)
      image: bitnami/git
      script: |
        # (script content)
  workspaces:
    - name: workspace
    - name: ssh-directory

